<div class="copyright" style = "text-align: center;">
  {% set current = date(Date.now(), "YYYY") %}
  &copy; {% if theme.since and theme.since != current %} {{ theme.since }} - {% endif %}
  <span itemprop="copyrightYear">2016 - {{ current }}</span>

<div class="powered-by">
    Powered By <a href="mailto:wuxiaohu@youzan.com">Xiaohu</a>
</div>

<div class="theme-info">
    Technical Supported By Hexo-Themes-Next And Github
</div>
</div>
